// Package docs Code generated by swaggo/swag. DO NOT EDIT.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
  "schemes": {{ marshal .Schemes }},
  "swagger": "2.0",
  "info": {
    "description": "{{escape .Description}}",
    "title": "{{.Title}}",
    "contact": {},
    "version": "{{.Version}}"
  },
  "host": "{{.Host}}",
  "basePath": "{{.BasePath}}",
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "paths": {
    "/health": {
      "get": {
        "description": "Service is up",
        "produces": ["text/plain"],
        "tags": ["system"],
        "summary": "Health check",
        "responses": {
          "200": {
            "description": "ok",
            "schema": { "type": "string" }
          }
        }
      }
    },

    "/messages": {
      "get": {
        "description": "Returns messages for a conversation",
        "produces": ["application/json"],
        "tags": ["messages"],
        "summary": "List messages",
        "parameters": [
          {
            "type": "string",
            "description": "Conversation ID",
            "name": "conversationId",
            "in": "query",
            "required": true
          },
          {
            "type": "integer",
            "default": 50,
            "description": "Max number of messages",
            "name": "limit",
            "in": "query"
          }
        ],
        "security": [{ "BearerAuth": [] }],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "additionalProperties": true
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "additionalProperties": { "type": "string" }
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": { "type": "string" }
          }
        }
      }
    },

    "/auth/register": {
      "post": {
        "description": "Kullanıcı kayıt olur (JSON body)",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "tags": ["auth"],
        "summary": "Register",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/RegisterRequest" }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": { "$ref": "#/definitions/AuthTokenResponse" }
          },
          "400": {
            "description": "Bad Request",
            "schema": { "type": "string" }
          },
          "409": {
            "description": "Conflict (email already exists)",
            "schema": { "type": "string" }
          }
        }
      }
    },

    "/auth/login": {
      "post": {
        "description": "Giriş (email + password). Başarılı olursa accessToken döner ve refresh_token cookie set edilir.",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "tags": ["auth"],
        "summary": "Login",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/LoginRequest" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": { "$ref": "#/definitions/AuthLoginResponse" }
          },
          "400": { "description": "Bad Request", "schema": { "type": "string" } },
          "401": { "description": "Unauthorized", "schema": { "type": "string" } }
        }
      }
    },

    "/auth/refresh": {
      "post": {
        "description": "Refresh token cookie ile yeni accessToken üretir.",
        "produces": ["application/json"],
        "tags": ["auth"],
        "summary": "Refresh",
        "responses": {
          "200": {
            "description": "OK",
            "schema": { "$ref": "#/definitions/RefreshResponse" }
          },
          "401": { "description": "Unauthorized", "schema": { "type": "string" } }
        }
      }
    },

    "/auth/logout": {
      "post": {
        "description": "Refresh cookie expire eder.",
        "tags": ["auth"],
        "summary": "Logout",
        "responses": {
          "204": { "description": "No Content" }
        }
      }
    }
  },

  "definitions": {
    "RegisterRequest": {
      "type": "object",
      "required": ["name", "email", "password"],
      "properties": {
        "name": { "type": "string", "example": "Adile" },
        "email": { "type": "string", "example": "adile.karci@hotmail.com" },
        "password": { "type": "string", "example": "Zeynep@44" }
      }
    },

    "LoginRequest": {
      "type": "object",
      "required": ["email", "password"],
      "properties": {
        "email": { "type": "string", "example": "adile.karci@hotmail.com" },
        "password": { "type": "string", "example": "Zeynep@44" }
      }
    },

    "UserPublic": {
      "type": "object",
      "properties": {
        "id": { "type": "string", "example": "c0a8012e-3b3e-4f34-8c07-1c27f2e8a3c1" },
        "name": { "type": "string", "example": "Adile" }
      }
    },

    "AuthTokenResponse": {
      "type": "object",
      "properties": {
        "accessToken": { "type": "string" },
        "user": {
          "type": "object",
          "additionalProperties": true
        }
      }
    },

    "AuthLoginResponse": {
      "type": "object",
      "properties": {
        "accessToken": { "type": "string" },
        "user": { "$ref": "#/definitions/UserPublic" }
      }
    },

    "RefreshResponse": {
      "type": "object",
      "properties": {
        "accessToken": { "type": "string" }
      }
    }
  },

  "securityDefinitions": {
    "BearerAuth": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Vue-WhatsApp API",
	Description:      "API documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
